import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Браслеты (8 products)
        {
            name: 'Браслет из паракорда "Классика"',
            price: 590,
            description: 'Прочный браслет из паракорда 550 типа. Выдерживает нагрузку до 250 кг. Идеален для походов, туризма и повседневной носки.',
            category: 'Браслеты',
            images: ['/images/bracelet-classic-1.jpg', '/images/bracelet-classic-2.jpg', '/images/bracelet-classic-3.jpg'],
            material: 'паракорд 550',
            featured: true,
            isNew: false,
            isBestseller: true,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Кобра"',
            price: 690,
            description: 'Классическое плетение "Кобра" из качественного паракорда. Удобная застежка-фастекс. Подходит для активного отдыха и повседневной носки.',
            category: 'Браслеты',
            images: ['/images/bracelet-cobra-1.jpg', '/images/bracelet-cobra-2.jpg', '/images/bracelet-cobra-3.jpg', '/images/bracelet-cobra-4.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: true,
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-09-01').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Кобра MAXI"',
            price: 790,
            description: 'Усиленная версия классической "Кобры" с двойным плетением. Больше паракорда в запасе. Максимальная прочность и надежность.',
            category: 'Браслеты',
            images: ['/images/bracelet-cobra-maxi-1.jpg', '/images/bracelet-cobra-maxi-2.jpg', '/images/bracelet-cobra-maxi-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: true,
            isBestseller: true,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Морской узел"',
            price: 650,
            description: 'Оригинальное плетение в стиле морских узлов. Стильный дизайн и высокая функциональность. Отлично подходит для любителей морской тематики.',
            category: 'Браслеты',
            images: ['/images/bracelet-naval-1.jpg', '/images/bracelet-naval-2.jpg', '/images/bracelet-naval-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-07-10').toISOString(),
            updatedAt: new Date('2024-07-10').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Рыбий хвост"',
            price: 720,
            description: 'Элегантное плетение "Рыбий хвост" с плоским профилем. Комфортно сидит на руке. Идеальный вариант для ежедневного ношения.',
            category: 'Браслеты',
            images: ['/images/bracelet-fishtail-1.jpg', '/images/bracelet-fishtail-2.jpg', '/images/bracelet-fishtail-3.jpg', '/images/bracelet-fishtail-4.jpg'],
            material: 'паракорд 550',
            featured: true,
            isNew: false,
            isBestseller: true,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Акула"',
            price: 850,
            description: 'Сложное объемное плетение "Акула" для настоящих ценителей. Максимальный запас паракорда. Выглядит эффектно и стильно.',
            category: 'Браслеты',
            images: ['/images/bracelet-shark-1.jpg', '/images/bracelet-shark-2.jpg', '/images/bracelet-shark-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: true,
            isBestseller: false,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Удав"',
            price: 780,
            description: 'Плотное тугое плетение "Удав" с характерным рисунком. Очень прочный и долговечный. Отличный выбор для экстремальных условий.',
            category: 'Браслеты',
            images: ['/images/bracelet-boa-1.jpg', '/images/bracelet-boa-2.jpg', '/images/bracelet-boa-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            name: 'Браслет из паракорда "Королевская кобра"',
            price: 890,
            description: 'Премиум плетение "Королевская кобра" с двойным слоем. Максимум паракорда и стиля. Идеальный подарок для любителя тактического снаряжения.',
            category: 'Браслеты',
            images: ['/images/bracelet-king-cobra-1.jpg', '/images/bracelet-king-cobra-2.jpg', '/images/bracelet-king-cobra-3.jpg', '/images/bracelet-king-cobra-4.jpg'],
            material: 'паракорд 550',
            featured: true,
            isNew: true,
            isBestseller: true,
            createdAt: new Date('2024-11-10').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        
        // Жетоны (4 products)
        {
            name: 'Армейский жетон стандарт',
            price: 490,
            description: 'Армейский жетон из нержавеющей стали с лазерной гравировкой. Подходит для военнослужащих и любителей милитари стиля. Стандартный размер 50x29 мм.',
            category: 'Жетоны',
            images: ['/images/tag-standard-1.jpg', '/images/tag-standard-2.jpg', '/images/tag-standard-3.jpg'],
            material: 'сталь нержавеющая',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        {
            name: 'Армейский жетон премиум',
            price: 790,
            description: 'Премиальный жетон из утолщенной стали с глубокой гравировкой. Повышенная износостойкость. Включает силиконовую окантовку для бесшумности.',
            category: 'Жетоны',
            images: ['/images/tag-premium-1.jpg', '/images/tag-premium-2.jpg', '/images/tag-premium-3.jpg', '/images/tag-premium-4.jpg'],
            material: 'сталь нержавеющая',
            featured: false,
            isNew: false,
            isBestseller: true,
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            name: 'Жетон с гравировкой',
            price: 690,
            description: 'Персонализированный жетон с индивидуальной гравировкой. Можно нанести имя, группу крови, важную информацию. Изготовление 2-3 дня.',
            category: 'Жетоны',
            images: ['/images/tag-custom-1.jpg', '/images/tag-custom-2.jpg', '/images/tag-custom-3.jpg'],
            material: 'сталь нержавеющая',
            featured: true,
            isNew: true,
            isBestseller: false,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            name: 'Жетон тактический',
            price: 590,
            description: 'Тактический жетон черного цвета с матовым покрытием. Не бликует на солнце. Идеален для страйкбола, охоты и тактических игр.',
            category: 'Жетоны',
            images: ['/images/tag-tactical-1.jpg', '/images/tag-tactical-2.jpg', '/images/tag-tactical-3.jpg'],
            material: 'сталь нержавеющая',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        
        // Брелоки (4 products)
        {
            name: 'Брелок из паракорда "Обезьянка"',
            price: 290,
            description: 'Компактный брелок из паракорда, сплетенный вручную. Удобен для ключей, рюкзаков. Может служить как аварийный запас шнура длиной до 1 метра.',
            category: 'Брелоки',
            images: ['/images/keychain-monkey-1.jpg', '/images/keychain-monkey-2.jpg', '/images/keychain-monkey-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-08-01').toISOString(),
            updatedAt: new Date('2024-08-01').toISOString(),
        },
        {
            name: 'Брелок из паракорда "Кулак"',
            price: 390,
            description: 'Плотный брелок плетением "Кулак" с металлическим шариком внутри. Может использоваться для самообороны. Стильный аксессуар для ключей.',
            category: 'Брелоки',
            images: ['/images/keychain-fist-1.jpg', '/images/keychain-fist-2.jpg', '/images/keychain-fist-3.jpg', '/images/keychain-fist-4.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            name: 'Брелок тактический EDC',
            price: 490,
            description: 'Многофункциональный EDC брелок из паракорда с карабином и свистком. Незаменимый помощник на каждый день. Компактный и надежный.',
            category: 'Брелоки',
            images: ['/images/keychain-edc-1.jpg', '/images/keychain-edc-2.jpg', '/images/keychain-edc-3.jpg'],
            material: 'комбинированный',
            featured: false,
            isNew: true,
            isBestseller: false,
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },
        {
            name: 'Брелок-темляк для ножа',
            price: 350,
            description: 'Специальный темляк из паракорда для ножей и мультитулов. Удобная петля для запястья. Предотвращает потерю инструмента в походных условиях.',
            category: 'Брелоки',
            images: ['/images/keychain-lanyard-1.jpg', '/images/keychain-lanyard-2.jpg', '/images/keychain-lanyard-3.jpg'],
            material: 'паракорд 550',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-07-25').toISOString(),
        },
        
        // Коробочки (4 products)
        {
            name: 'Деревянная коробка для жетонов',
            price: 890,
            description: 'Деревянная подарочная коробка ручной работы. Идеально подходит для хранения жетонов, браслетов или других памятных вещей. Размер 15x10x5 см.',
            category: 'Коробочки',
            images: ['/images/box-wooden-1.jpg', '/images/box-wooden-2.jpg', '/images/box-wooden-3.jpg'],
            material: 'дерево',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            name: 'Подарочная коробка премиум',
            price: 1500,
            description: 'Премиальная коробка из массива дуба с гравировкой. Бархатная внутренняя отделка. Идеальный подарок для особого случая. Размер 20x15x7 см.',
            category: 'Коробочки',
            images: ['/images/box-premium-1.jpg', '/images/box-premium-2.jpg', '/images/box-premium-3.jpg', '/images/box-premium-4.jpg'],
            material: 'дерево',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            name: 'Футляр для браслета',
            price: 390,
            description: 'Компактный мягкий футляр для хранения и транспортировки браслетов. Защищает от пыли и повреждений. Удобно брать в дорогу.',
            category: 'Коробочки',
            images: ['/images/box-case-1.jpg', '/images/box-case-2.jpg', '/images/box-case-3.jpg'],
            material: 'комбинированный',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-01').toISOString(),
        },
        {
            name: 'Набор "Коробка + жетон + браслет"',
            price: 2500,
            description: 'Готовый подарочный набор в деревянной коробке. Включает браслет "Кобра", армейский жетон премиум и сертификат. Отличный подарок мужчине.',
            category: 'Коробочки',
            images: ['/images/box-set-1.jpg', '/images/box-set-2.jpg', '/images/box-set-3.jpg', '/images/box-set-4.jpg'],
            material: 'комбинированный',
            featured: false,
            isNew: false,
            isBestseller: false,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});